### PR TITLE
fix: "The decoded text message was too big for the output buffer and …

### PR DESCRIPTION
**Pull request by tuxmartin**
fix: "The decoded text message was too big for the output buffer"

This solve my issue: https://github.com/daniel-sc/rocketchat-modern-client/issues/13

I changed the buffer size according to this guide: 
https://stackoverflow.com/a/47384096

I chose 4MB at random. It's hopeful "big enough number". And it works great for me without any error.

### CODE REVIEW

**Comment by daniel-sc** [comment]
Hi @tuxmartin 
Thanks for this contribution! 2 questions:
- Per https://docs.oracle.com/javaee/7/api/javax/websocket/OnMessage.html#maxMessageSize— a value of `-1` should be interpreted as „no limit“. Did you try to set this explicitly?
- Is it possible to make this number configurable/overwritable the the user?

**Comment by daniel-sc** [comment]
Or even better: use http://docs.oracle.com/javase/7/docs/api/java/io/Reader.html?is-external=true instead of `String` as Parameter? (This really should prevent any limits?)

**Comment by daniel-sc** [comment]
Hi @tuxmartin , I updated this PR for the suggested Reader - can you test if this as well resolves the problem?

**Comment by tuxmartin** [comment]
Hi @daniel-sc,

I apologize for the delay.

I tried -1 and reader:
```java
@OnMessage (maxMessageSize = -1) // no limit
public void onMessage (String message) {

public void onMessage (Reader message) {
```

Both solutions crash on the same error: `The decoded text message was too big for the output buffer and the endpoint does not support partial messages`

From what I've tried so far, only the following works:

```java
@OnMessage (maxMessageSize = 4194304) // 4 MiB
public void onMessage (String message)
```

The value should definitely be able to change.
I don't know the right value. 4MB works for me, but it doesn't have to be good for others.

**Comment by daniel-sc** [comment]
Hi @tuxmartin ,
thanks for the feedback. I have one last shot at a solution without some hard coded limit: Using message parts. Could you please test this (last commit) and tell me if it resolves the issue?

**Comment by tuxmartin** [comment]
Hi @daniel-sc,
it works!

**Pull request merged**
