### PR TITLE
Add alias and avatar params to SendMessage.

### PR DESCRIPTION
**Pull request by tuxmartin**

### CODE REVIEW

**Comment by daniel-sc** [comment]
Hi @tuxmartin 

thanks for your contribution!

Would it make sense to extend `SendMessageParams` with further optional fields instead of duplicating it in  `SendMessageExtendedParams`? If you agree, would you mind to refactor?

I'll look into the travis build meanwhile..

Best, Daniel

**Comment by daniel-sc** [comment]
I fixed the failing builds on master, if you can please rebase (or merge) this branch onto the new version of master the build here should succeed as well. (If you need help with that, please let me know!)

**Comment by tuxmartin** [comment]
Hi @daniel-sc,

I agree with any refactor.

I'm Java begginer, so I was glad that my changes it worked at least somehow.

But I think is better to send pull request (with not good cood, but working) , than only create new issue.

I'm writing simple rocket chat notificator, that control imap mailboxes and send message to chat if there is new mail. After mail is not present in inbox folder, I need to strikethrough message text - edit meesage and add `~` to begin and end of message. I have msgIDs in MySQL.
For that I need [update message](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/update-message/).

I would like to set mail image as avatar and something like "MAIL: mail@example.net" as alias (each mailbox will have own address in alias).

If `rocketchat-modern-client` will support sending message with custom avatar and alias and have `updateMessage` function, it will be great!

Can you please add `updateMessage` https://rocket.chat/docs/developer-guides/realtime-api/method-calls/update-message/ ?

Thank you.

**Comment by daniel-sc** [comment]
Hi @tuxmartin 

just merged this PR. And providing PRs instead of issues is of course a great sprit!! 🥇 

As I am rather busy currently, can you as well create an PR for the `updateMessage`? I'm happy to help when there are problems and to create a new release once this done.

Best, Daniel

**Pull request merged**
