### PR TITLE
Add support for change/remove attachments in updateMessage.

### PR DESCRIPTION
**Pull request by tuxmartin**
In my notificator app I send mesage with title and attachments and after user acknowledge it, I send update only with title **without** attachments.

### CODE REVIEW

**Comment by daniel-sc** [comment]
Hi @tuxmartin 

could you refactor this so that `updateMessage(String msg, String _id)` simply uses `updateMessageWithAttachments(String msg, String _id, List<Attachment> attachments)`? Then I'm happy to merge :)

**Comment by tuxmartin** [comment]
Hi @daniel-sc 

is it ok now?

I don't have reference to existing list of `attachments`, so I need to create new empty list - but this delete all existing  `attachments`.
https://github.com/daniel-sc/rocketchat-modern-client/blob/d30986452681be641c1ac9ebf52604f54a19167b/src/main/java/com/github/daniel_sc/rocketchat/modern_client/RocketChatClient.java#L113
How can I do it better?

**Comment by daniel-sc** [comment]
Did you try using `null` instead of `new ArrayList<..>`?

**Comment by tuxmartin** [comment]
@daniel-sc thank you. It works.

**Pull request merged**
